### ISSUE TITLE
大哥，protobuf文件里面怎么没内容呀？

### ISSUE THREAD

**Issue by bestbelief** [sclausen/angular2-protobuf-mqtt-example#2]
求解，我把项目克隆下来无法运行，
显示这个有问题import * as root from '../protobuf/value.protobuf.js';
value.protobuf.js没找到
是什么原因啊？

**Comment by sclausen** [comment]
I'm really sorry, I know chinese is one of the most spoken languages in the world, but I'm afraid that most of the internet community prefers english. Would you mind choosing english as the language in your issue?

**Comment by sclausen** [comment]
由于不活动而关闭
